### ISSUE TITLE
3D version snow tend to fall apart	?

### ISSUE THREAD

**Issue by foxhuntd** [Azmisov/snow#2]
Hi, guys
This solver is very inspiring. 
But 3D houdini version snow always tend to fall apart like sand.
It can not produce chunky parts like original paper or 2d version.

**Comment by foxhuntd** [comment]
Sorry bother your guys.
The problem is caused by timstep.
When timstep was too big, snow behave like goo.
When timstep small enough, snow stay chunky.

**Comment by Azmisov** [comment]
Yeah, I'm pretty sure the implementation is correct, mathematically and all. But it's still difficult to get results that look like the demo video Disney put out. If the timestep isn't small enough, the snow becomes unstable and seems to just fall apart. Unfortunately, to get good results, the timestep needs to be really small. The implicit solver mentioned in the paper can apparently help make the simulations more stable. However, the paper is pretty cryptic about the details of the implicit solver, so I was never able to get it working in 2D (I was porting over all the 2D code directly to the 3D version; as it stands, both 2D and 3D versions lack the implicit solver). The slow simulation times (due to the small timesteps) was one of the criticisms many have had of this snow simulation method.

Another reason the snow can look sandy is due to the snow shader or surfacer. I think the surfacer is probably the trickiest; too small a radius, and it looks like sand; too big and it looks like goo. It would have been nice if the paper discussed in more detail how they got their snow to look so good in renders.
